version: 2.1

jobs:
  build:
    docker:
      - image: node:latest

    working_directory: /app

    steps:
      - checkout

      # Build du container
      - run:
          name: Build node-js-sample
          command: docker build -t node-js-sample:latest .

      # Run du container
      - run:
          name: Run node-js-sample
          command: docker run -p 8080:8080 node-js-sample

      # Installation de Curl
      - run:
          name: Installation Curl
          command: apt install -y curl

      # Status code
      - run:
          name: Status Code
          command: curl -I 192.168.198.130:8080
