version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true

    steps:
      - checkout

      # Build du container
      - run:
          name: Build node-js-sample
          command: docker pull sampcn/node-js-sample:latest

      # Run du container
      - run:
          name: Run node-js-sample
          command: docker run -p 8080:8080 -d --name node-js-app sampcn/node-js-sample:latest

      # Timesleep
      - run:
          name: Wait for Container to Start
          command: sleep 10

      # Status code
      - run:
          name: Check status Code
          command: docker exec -it node-js-app curl -I http://localhost:8080


      # Login on DockerHub
      - run:
          name: Login on DockerHub
          command: sudo docker login -u "${DOCKER_HUB_USERNAME}" -p "${DOCKER_HUB_PASSWD}"

      # Publish image on DockerHub
      - run:
          name: Publish image on DockerHub
          command: sudo docker push sampcn/node-js-sample:latest
