version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true

    steps:
      - checkout

      # Build du container
      - run:
          name: Build node-js-sample
          command: docker pull sampcn/node-js-sample:latest

      # Run du container
      - run:
          name: Run node-js-sample
          command: docker run -p 8080:8080 -d --name node-js-app sampcn/node-js-sample:latest

      # Installation de Curl
      - run:
          name: Installation Curl
          command: docker exec -it node-js-app apt install -y curl

      # Status code
      - run:
          name: Status Code
          command: docker exec -it node-js-app curl -I 192.168.198.130:8080
