version: 2.1

jobs:
  build:
    docker:
      - image: node:latest

    working_directory: /app

    machine:
      image: ubuntu:latest

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      # Build du container
      - run:
          name: Build node-js-sample
          command: docker pull sampcn/node-js-sample:latest

      # Run du container
      - run:
          name: Run node-js-sample
          command: docker run -p 8080:8080 --name node-js-sample sampcn/node-js-sample:latest

      # Installation de Curl
      - run:
          name: Installation Curl
          command: apt install -y curl

      # Status code
      - run:
          name: Status Code
          command: curl -I 192.168.198.130:8080
