version: 2.1

jobs:
  build:
    docker:
      - image: node:latest

    working_directory: /app

    steps:
      - checkout

      # Installer les dépendances
      - run:
          name: Install Dependencies
          command: npm install

jobs:
  build: Curl
    machine:
      image: ubuntu:latest

    steps:
      - run:
          name: Status Code
          command: curl -I 192.168.198.130:8080
